# Global Settings
default-wand:
  material: BLAZE_ROD
  display-name: "&6AFK Zone Selector"
  lore:
    - "&7Use this wand to select"
    - "&7the corners of your"
    - "&7AFK zone."

auto-save-interval: 300 # Seconds
time-format: "mm:ss"

# Default Rewards (applied if no zone-specific rewards exist)
default-rewards:
  - "eco give %player% 10"
  - "give %player% diamond 1"