name: NexusAFKZone
main: nexus.nexusAFKZone.NexusAFKZone
version: 1.4
api-version: 1.20
commands:
  afkzone:
    description: AFK Zone commands
    usage: /afkzone <subcommand> [arguments]
    aliases: [afkz]
permissions:
  nexusafkzone.command.create:
    description: Allows creating an AFK zone
    default: op
  nexusafkzone.command.delete:
    description: Allows deleting an AFK zone
    default: op
  nexusafkzone.command.reload:
    description: Allows reloading the plugin
    default: op
  nexusafkzone.command.list:
    description: Allows listing all AFK zones
    default: op
  nexusafkzone.zone:
    description: Base permission for AFK zones
    default: op